### ISSUE TITLE
can't find " ns3/epidemic-routing-module.h"

### ISSUE THREAD

**Issue by ZoeJiang2222** [dadada/ns-3-leo#3]
Thanks for all you have done, I'm working on import this module into ns3, but there's something wrong when running examples, the fatal error is " fatal error: ns3/epidemic-routing-module.h: can't find this document or menu".
Can you just help me figure it out? I suspect that maybe **the version of ns3 and ubuntu** results that error, I'm using ns3.34 and ubuntu18.04, can you tell me the limits of version? Or where can I find "epidemic-routing-module.h“？
By the way, I'm tring to use this module to product  datasets for satellite routing, can I modify this module to make it?

**Comment by ZoeJiang2222** [comment]
Sorry to disturb you, I have already found this module.
And I wonder have you or anybody else ever tried to apply this module with ns3-gym for satellite routing optimization?
Thanks a lot for all you’ve done.

**Comment by dadada** [comment]
Sorry, for the late reply. Glad you could resolve your issue.

> And I wonder have you or anybody else ever tried to apply this module with ns3-gym for satellite routing optimization?

Not that I know of, but I don't currently follow the research in this field. So there might be something I do not know of. The satellite positions / link metrics are time-dependent but also very deterministic. So I would assume the most effective way would be to centrally compute routes based on the current / expected traffic patterns in the regions and known satellite positions. This may be done using reinforcement learning, or conventional routing algorithms (Dijkstra) using the appropriate metrics.

**Comment by ZoeJiang2222** [comment]
Dear Tim,

thanks for your reply, I totally agree with you, and ns3-gym is just specifically designed for reinforcement learning, it provides an interface so that ns3 can work as the environment with agents written in Python.
But I’m a little confused after reading the example of “leo-delay-tracing”, it seems like we can only get the delay from one ground station to another(which is defined by setting altitude and longitude), satellites are defined as “constellation”, but as you say, I just want to research the routing metrics of ISL, can you guide me how to make it?
Sincerely thank you again for your help.

Zoe
